### ISSUE TITLE
Questionable glyph for U+AA5E CHAM PUNCTUATION DOUBLE DANDA

### ISSUE THREAD

**Issue by dscorbett** [notofonts/cham#1]
### Font 
NotoSansCham-Regular.ttf

### Where the font came from, and when
Site: https://noto-website-2.storage.googleapis.com/pkgs/NotoSansCham-unhinted.zip
Date: 2018-03-04

### Font Version
Version 2.000;GOOG;noto-source:20170915:90ef993387c0

### Issue
The glyph for U+AA5E CHAM PUNCTUATION DOUBLE DANDA has three dots on top. The double danda has no dots in its Unicode code chart and Unicode proposals, and the other Cham dandas have no dots even in this font. Should the double danda look like that?

### Character data
꩞
U+AA5E CHAM PUNCTUATION DOUBLE DANDA

### Screenshot
![꩞](https://user-images.githubusercontent.com/1124347/36956755-124d30c2-1ffe-11e8-9694-a3953551589d.png)

**Comment by ohbendy** [comment]
> Remove three dots?

On what basis?

**Comment by simoncozens** [comment]
Since this may be a stylistic issue, I've added a dotless form as a stylistic set.
