### ISSUE TITLE
Does not build

### ISSUE THREAD

**Issue by aelatham** [notofonts/cham#10]
One check was not successful, so the "rebuild website" check also failed.

**Comment by simoncozens** [comment]
I don't think that's true. The release run built the font but did not successfully make a Google Fonts PR; but that run purposefully does not rebuild the website (the grey cross means "skipped"):

<img width="970" alt="Screenshot 2024-05-17 at 06 51 03" src="https://github.com/notofonts/cham/assets/106728/8dd75ce8-f2af-432d-9497-542e69d23099">


The run before that completed successfully, and rebuilt the website, causing a "pages build and deployment" action to run:

<img width="1063" alt="Screenshot 2024-05-17 at 06 51 25" src="https://github.com/notofonts/cham/assets/106728/48e0201d-6a8d-439f-86da-0721e7a1cc86">
